---
    - name: Create nginx http conf
      template:
        src: ttserg.devops.srwx.net.http.conf.j2
#        src: /srv/ansible/templates/{{ v_sitename }}.j2
#        dest: /etc/nginx/sites-available/{{ v_sitename }}.conf
        dest: /etc/nginx/sites-available/ttserg.devops.srwx.net.http.conf
        owner: root 
        group: root 
        mode: 0644   
      notify: restart nginx
   
#   - name: Force nginx reloads

    - name: Create symlink
      file: 
        src: /etc/nginx/sites-available/ttserg.devops.srwx.net.http.conf
        dest: /etc/nginx/sites-enabled/ttserg.devops.srwx.net.http.conf
        state: link
      notify: restart nginx

#    - name: Force nginx reloads

